imports:
    # - { resource: routing.yml }
    # - { resource: security.yml }

framework:
    translator: ~

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: GreenFrog\Bundle\CmsBundle\Entity\User
    registration:
      confirmation:
        enabled: true
        from_email:
          address: noreply@free.fr
          sender_name: Sender Name
        template: GreenFrogUserBundle:User:confirm_email.html.twig
green_frog_cms:
    site:
      name: Sitename
      title: Homepage title
      page_title: Pages title